/**
 * All HTTP routes mounted in app.ts — single source for OpenAPI and README tables.
 */
export type HttpMethod = 'get' | 'post' | 'put' | 'delete';

export interface RouteCatalogEntry {
  method: HttpMethod;
  /** Full path including mount prefix, Express style (:param) */
  path: string;
  summary: string;
  tag: string;
  auth: 'none' | 'jwt' | 'jwt-admin';
  /** Optional request body example (POST/PUT) */
  requestExample?: Record<string, unknown>;
  /** Optional JSON response example */
  responseExample?: Record<string, unknown> | unknown[];
  notes?: string;
}

export const routeCatalog: RouteCatalogEntry[] = [
  // ── Public ─────────────────────────────────────────────────────────────────
  {
    method: 'get',
    path: '/health',
    summary: 'Health check',
    tag: 'System',
    auth: 'none',
    responseExample: { status: 'OK', timestamp: '2026-05-30T12:00:00.000Z' },
  },
  {
    method: 'get',
    path: '/api',
    summary: 'API index (docs link, demo user hint)',
    tag: 'System',
    auth: 'none',
    responseExample: {
      message: 'Inwest App Backend API',
      docs: '/api/docs',
      demoUser: 'demo@demo.com',
    },
  },

  // ── Auth ───────────────────────────────────────────────────────────────────
  {
    method: 'post',
    path: '/api/auth/register',
    summary: 'Register a new user',
    tag: 'Auth',
    auth: 'none',
    requestExample: {
      email: 'user@example.com',
      password: 'SecurePass1',
      firstName: 'Jan',
      lastName: 'Kowalski',
    },
    responseExample: {
      accessToken: 'eyJhbG...',
      refreshToken: 'uuid',
      user: { id: '...', email: 'user@example.com' },
    },
  },
  {
    method: 'post',
    path: '/api/auth/login',
    summary: 'Login and receive JWT tokens',
    tag: 'Auth',
    auth: 'none',
    requestExample: { email: 'demo@demo.com', password: 'Demo1234!' },
    responseExample: {
      accessToken: 'eyJhbG...',
      refreshToken: 'uuid',
      user: { id: '...', email: 'demo@demo.com' },
    },
  },
  {
    method: 'post',
    path: '/api/auth/refresh',
    summary: 'Refresh access token',
    tag: 'Auth',
    auth: 'none',
    requestExample: { refreshToken: 'uuid-refresh-token' },
  },
  {
    method: 'post',
    path: '/api/auth/logout',
    summary: 'Revoke refresh token',
    tag: 'Auth',
    auth: 'none',
    requestExample: { refreshToken: 'uuid-refresh-token' },
  },
  {
    method: 'get',
    path: '/api/auth/me',
    summary: 'Current authenticated user profile',
    tag: 'Auth',
    auth: 'jwt',
    responseExample: {
      id: 'uuid',
      email: 'demo@demo.com',
      firstName: 'Demo',
      lastName: 'User',
      role: 'user',
    },
  },
  {
    method: 'get',
    path: '/api/auth/admin/ping',
    summary: 'Admin-only health ping',
    tag: 'Auth',
    auth: 'jwt-admin',
    responseExample: { ok: true },
  },

  // ── Portfolio (core e-business) ────────────────────────────────────────────
  {
    method: 'get',
    path: '/api/portfolio',
    summary: 'List portfolio holdings',
    tag: 'Portfolio',
    auth: 'jwt',
    responseExample: [
      { id: 1, symbol: 'AAPL', quantity: '5', averageCost: '180', assetType: 'stock' },
    ],
  },
  {
    method: 'get',
    path: '/api/portfolio/summary',
    summary: 'Portfolio summary (totals, gain/loss)',
    tag: 'Portfolio',
    auth: 'jwt',
  },
  {
    method: 'post',
    path: '/api/portfolio',
    summary: 'Add portfolio holding',
    tag: 'Portfolio',
    auth: 'jwt',
    requestExample: {
      symbol: 'AAPL',
      quantity: '5',
      averageCost: '180.50',
      assetType: 'stock',
    },
    responseExample: {
      id: 1,
      symbol: 'AAPL',
      quantity: '5',
      averageCost: '180.50',
      assetType: 'stock',
    },
  },
  {
    method: 'post',
    path: '/api/portfolio/refresh-prices',
    summary: 'Refresh current prices for user holdings',
    tag: 'Portfolio',
    auth: 'jwt',
  },
  {
    method: 'put',
    path: '/api/portfolio/:id',
    summary: 'Update portfolio holding',
    tag: 'Portfolio',
    auth: 'jwt',
    requestExample: { quantity: '10', averageCost: '175.00' },
  },
  {
    method: 'delete',
    path: '/api/portfolio/:id',
    summary: 'Delete portfolio holding',
    tag: 'Portfolio',
    auth: 'jwt',
    responseExample: { success: true, message: 'Portfolio entry deleted' },
  },

  // ── Watchlist ──────────────────────────────────────────────────────────────
  {
    method: 'get',
    path: '/api/watchlist',
    summary: 'List watchlist symbols',
    tag: 'Watchlist',
    auth: 'jwt',
    responseExample: [{ id: 1, symbol: 'MSFT', name: 'Microsoft', notes: 'Long-term' }],
  },
  {
    method: 'get',
    path: '/api/watchlist/:id',
    summary: 'Get single watchlist entry',
    tag: 'Watchlist',
    auth: 'jwt',
  },
  {
    method: 'post',
    path: '/api/watchlist',
    summary: 'Add symbol to watchlist',
    tag: 'Watchlist',
    auth: 'jwt',
    requestExample: { symbol: 'MSFT', name: 'Microsoft', notes: 'Long-term watch' },
  },
  {
    method: 'put',
    path: '/api/watchlist/:id',
    summary: 'Update watchlist entry',
    tag: 'Watchlist',
    auth: 'jwt',
    requestExample: { notes: 'Updated note' },
  },
  {
    method: 'delete',
    path: '/api/watchlist/:id',
    summary: 'Remove watchlist entry',
    tag: 'Watchlist',
    auth: 'jwt',
  },

  // ── Calendar ───────────────────────────────────────────────────────────────
  {
    method: 'get',
    path: '/api/calendar/events',
    summary: 'Calendar events and reminders in date range',
    tag: 'Calendar',
    auth: 'jwt',
    notes: 'Query: from, to (YYYY-MM-DD), optional symbol, type',
  },
  {
    method: 'post',
    path: '/api/calendar/reminders',
    summary: 'Create personal reminder',
    tag: 'Calendar',
    auth: 'jwt',
    requestExample: {
      title: 'Earnings call',
      start: '2026-06-01',
      end: '2026-06-01',
      symbol: 'AAPL',
    },
  },
  {
    method: 'put',
    path: '/api/calendar/reminders/:id',
    summary: 'Update reminder',
    tag: 'Calendar',
    auth: 'jwt',
    requestExample: { title: 'Updated title', start: '2026-06-02' },
  },
  {
    method: 'delete',
    path: '/api/calendar/reminders/:id',
    summary: 'Delete reminder',
    tag: 'Calendar',
    auth: 'jwt',
  },

  // ── Market ─────────────────────────────────────────────────────────────────
  {
    method: 'get',
    path: '/api/market/search/:query',
    summary: 'Search symbols by query string',
    tag: 'Market',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/market/search',
    summary: 'Search symbols (query param q)',
    tag: 'Market',
    auth: 'jwt',
    notes: 'Query: q',
  },
  {
    method: 'get',
    path: '/api/market/movers',
    summary: 'Top market movers',
    tag: 'Market',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/market/overview',
    summary: 'Market overview snapshot',
    tag: 'Market',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/market/company/:symbol',
    summary: 'Company profile for symbol',
    tag: 'Market',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/market/news/:symbol',
    summary: 'News for symbol (optional path segment)',
    tag: 'Market',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/market/status',
    summary: 'Market data provider status',
    tag: 'Market',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/market/prices/:symbol',
    summary: 'Seeded historical prices (no external API key)',
    tag: 'Market',
    auth: 'jwt',
    responseExample: {
      symbol: 'AAPL',
      prices: [{ date: '2026-05-29', close: '190.12', open: '188.00' }],
    },
  },
  {
    method: 'get',
    path: '/api/market/usage',
    summary: 'Market API usage statistics',
    tag: 'Market',
    auth: 'jwt',
  },

  // ── Technical analysis ─────────────────────────────────────────────────────
  {
    method: 'get',
    path: '/api/technical/:symbol/chart',
    summary: 'OHLCV chart data with indicator arrays',
    tag: 'Technical',
    auth: 'jwt',
    notes: 'Query: timeframe, days, startDate, endDate, limit. Uses DB history; may backfill via Stooq when STOOQ_API_KEY is set.',
  },
  {
    method: 'get',
    path: '/api/technical/:symbol',
    summary: 'Technical analysis indicators for symbol',
    tag: 'Technical',
    auth: 'jwt',
    notes: 'Query: timeframe (default daily). Requires sufficient historical prices in DB.',
  },

  // ── Reddit ─────────────────────────────────────────────────────────────────
  {
    method: 'post',
    path: '/api/reddit/fetch',
    summary: 'Fetch Reddit posts for configured subreddits',
    tag: 'Reddit',
    auth: 'jwt',
    notes: 'Requires Reddit API keys (Account → API keys)',
  },
  { method: 'get', path: '/api/reddit/stats', summary: 'Reddit ingestion statistics', tag: 'Reddit', auth: 'jwt' },
  { method: 'get', path: '/api/reddit/trending', summary: 'Trending tickers from Reddit', tag: 'Reddit', auth: 'jwt' },
  { method: 'get', path: '/api/reddit/health', summary: 'Reddit integration health', tag: 'Reddit', auth: 'jwt' },
  {
    method: 'get',
    path: '/api/reddit/backfill/status',
    summary: 'Backfill job status',
    tag: 'Reddit',
    auth: 'jwt',
  },
  {
    method: 'post',
    path: '/api/reddit/backfill/chunk',
    summary: 'Run one backfill chunk',
    tag: 'Reddit',
    auth: 'jwt',
  },
  {
    method: 'post',
    path: '/api/reddit/backfill/smart-history',
    summary: 'Smart historical backfill',
    tag: 'Reddit',
    auth: 'jwt',
  },
  {
    method: 'post',
    path: '/api/reddit/sentiment/process',
    summary: 'Process sentiment for stored posts',
    tag: 'Reddit',
    auth: 'jwt',
  },
  {
    method: 'post',
    path: '/api/reddit/automated/start',
    summary: 'Start automated Reddit fetch',
    tag: 'Reddit',
    auth: 'jwt',
  },
  {
    method: 'post',
    path: '/api/reddit/automated/stop',
    summary: 'Stop automated Reddit fetch',
    tag: 'Reddit',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/reddit/automated/status',
    summary: 'Automated fetch status',
    tag: 'Reddit',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/reddit/posts/quality',
    summary: 'Quality-filtered Reddit posts',
    tag: 'Reddit',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/reddit/recommendations',
    summary: 'Stock recommendations from Reddit sentiment',
    tag: 'Reddit',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/reddit/sentiment/analytics',
    summary: 'Aggregate Reddit sentiment analytics',
    tag: 'Reddit',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/reddit/sentiment/stocks',
    summary: 'Per-stock Reddit sentiment scores',
    tag: 'Reddit',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/reddit/sentiment/history',
    summary: 'Historical Reddit sentiment series',
    tag: 'Reddit',
    auth: 'jwt',
  },

  // ── News ───────────────────────────────────────────────────────────────────
  {
    method: 'get',
    path: '/api/news/articles',
    summary: 'Fetch news articles',
    tag: 'News',
    auth: 'jwt',
    notes: 'preferCache=true (default): shared DB — no caller keys. Live fetch needs caller NewsData.io/Finnhub keys.',
  },
  {
    method: 'post',
    path: '/api/news/refresh',
    summary: 'Fetch fresh headlines (caller NewsData.io and/or Finnhub keys required)',
    tag: 'News',
    auth: 'jwt',
    requestExample: { limit: 25, hours: 24, category: 'general' },
  },
  {
    method: 'post',
    path: '/api/news/sentiment/analyze',
    summary: 'Analyze sentiment for news batch',
    tag: 'News',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/news/sentiment/trends/daily',
    summary: 'Daily news sentiment trends',
    tag: 'News',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/news/sentiment/analytics',
    summary: 'News sentiment analytics dashboard data',
    tag: 'News',
    auth: 'jwt',
  },
  {
    method: 'post',
    path: '/api/news/sentiment/text',
    summary: 'Score sentiment for arbitrary text',
    tag: 'News',
    auth: 'jwt',
    requestExample: { text: 'Apple beats earnings expectations' },
  },
  {
    method: 'get',
    path: '/api/news/sentiment/stock/:symbol',
    summary: 'News sentiment for a stock symbol',
    tag: 'News',
    auth: 'jwt',
  },

  // ── Alpaca (paper trading) ─────────────────────────────────────────────────
  {
    method: 'get',
    path: '/api/alpaca/account',
    summary: 'Alpaca paper account info',
    tag: 'Alpaca',
    auth: 'jwt',
    notes: 'Requires Alpaca API keys (Account → API keys)',
  },
  {
    method: 'get',
    path: '/api/alpaca/positions',
    summary: 'Open Alpaca positions',
    tag: 'Alpaca',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/alpaca/orders',
    summary: 'List Alpaca orders',
    tag: 'Alpaca',
    auth: 'jwt',
  },
  {
    method: 'post',
    path: '/api/alpaca/orders',
    summary: 'Place Alpaca paper order',
    tag: 'Alpaca',
    auth: 'jwt',
    requestExample: {
      symbol: 'AAPL',
      qty: 1,
      side: 'buy',
      type: 'market',
      time_in_force: 'day',
    },
  },
  {
    method: 'delete',
    path: '/api/alpaca/orders/:orderId',
    summary: 'Cancel Alpaca order',
    tag: 'Alpaca',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/alpaca/portfolio/history',
    summary: 'Alpaca portfolio history',
    tag: 'Alpaca',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/alpaca/watchlists',
    summary: 'Alpaca watchlists',
    tag: 'Alpaca',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/alpaca/assets',
    summary: 'Tradable Alpaca assets',
    tag: 'Alpaca',
    auth: 'jwt',
  },

  // ── Finnhub ────────────────────────────────────────────────────────────────
  {
    method: 'get',
    path: '/api/finnhub/quote/:symbol',
    summary: 'Finnhub real-time quote',
    tag: 'Finnhub',
    auth: 'jwt',
    notes: 'Requires Finnhub API key (Account → API keys)',
  },
  {
    method: 'get',
    path: '/api/finnhub/company/:symbol',
    summary: 'Finnhub company profile',
    tag: 'Finnhub',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/finnhub/news/:symbol',
    summary: 'Finnhub company news',
    tag: 'Finnhub',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/finnhub/news',
    summary: 'Finnhub general market news',
    tag: 'Finnhub',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/finnhub/search',
    summary: 'Finnhub symbol search',
    tag: 'Finnhub',
    auth: 'jwt',
    notes: 'Query: q',
  },
  {
    method: 'get',
    path: '/api/finnhub/financials/:symbol',
    summary: 'Finnhub financial statements',
    tag: 'Finnhub',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/finnhub/recommendations/:symbol',
    summary: 'Analyst recommendations',
    tag: 'Finnhub',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/finnhub/earnings/:symbol',
    summary: 'Earnings calendar for symbol',
    tag: 'Finnhub',
    auth: 'jwt',
  },

  // ── Alpha Vantage ──────────────────────────────────────────────────────────
  {
    method: 'get',
    path: '/api/alphavantage/quote/:symbol',
    summary: 'Alpha Vantage quote',
    tag: 'Alpha Vantage',
    auth: 'jwt',
    notes: 'Requires Alpha Vantage API key (Account → API keys)',
  },
  {
    method: 'get',
    path: '/api/alphavantage/overview/:symbol',
    summary: 'Alpha Vantage company overview',
    tag: 'Alpha Vantage',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/alphavantage/timeseries/:symbol',
    summary: 'Alpha Vantage time series',
    tag: 'Alpha Vantage',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/alphavantage/search',
    summary: 'Alpha Vantage symbol search',
    tag: 'Alpha Vantage',
    auth: 'jwt',
    notes: 'Query: keywords',
  },
  {
    method: 'get',
    path: '/api/alphavantage/movers',
    summary: 'Alpha Vantage top movers',
    tag: 'Alpha Vantage',
    auth: 'jwt',
  },

  // ── User profile ─────────────────────────────────────────────────────────────
  {
    method: 'get',
    path: '/api/user/profile',
    summary: 'Get user profile',
    tag: 'User',
    auth: 'jwt',
  },
  {
    method: 'put',
    path: '/api/user/profile',
    summary: 'Update user profile',
    tag: 'User',
    auth: 'jwt',
    requestExample: { firstName: 'Jan', lastName: 'Kowalski' },
  },
  {
    method: 'get',
    path: '/api/user/settings',
    summary: 'Get user settings',
    tag: 'User',
    auth: 'jwt',
  },
  {
    method: 'put',
    path: '/api/user/settings',
    summary: 'Update user settings',
    tag: 'User',
    auth: 'jwt',
    requestExample: { theme: 'dark', currency: 'USD' },
  },
  {
    method: 'get',
    path: '/api/user/integrations',
    summary: 'Integration status for current user (which services have DB keys)',
    tag: 'User',
    auth: 'jwt',
    responseExample: {
      integrations: { alpaca: true, reddit: false, news: false, finnhub: false, alphavantage: false },
      canUseAlpaca: true,
      canManageReddit: false,
      canFetchNews: false,
    },
  },
  {
    method: 'get',
    path: '/api/user/api-keys',
    summary: 'List stored API keys (masked)',
    tag: 'User',
    auth: 'jwt',
  },
  {
    method: 'post',
    path: '/api/user/api-keys',
    summary: 'Add external API key',
    tag: 'User',
    auth: 'jwt',
    requestExample: { name: 'Alpaca', service: 'alpaca', apiKey: 'PK...' },
  },
  {
    method: 'put',
    path: '/api/user/api-keys/:keyId',
    summary: 'Update API key',
    tag: 'User',
    auth: 'jwt',
  },
  {
    method: 'delete',
    path: '/api/user/api-keys/:keyId',
    summary: 'Delete API key',
    tag: 'User',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/user/security',
    summary: 'Security settings overview',
    tag: 'User',
    auth: 'jwt',
  },
  {
    method: 'post',
    path: '/api/user/security/2fa/enable',
    summary: 'Enable two-factor authentication',
    tag: 'User',
    auth: 'jwt',
  },
  {
    method: 'post',
    path: '/api/user/security/2fa/disable',
    summary: 'Disable two-factor authentication',
    tag: 'User',
    auth: 'jwt',
    requestExample: { password: 'Demo1234!' },
  },
  {
    method: 'put',
    path: '/api/user/change-password',
    summary: 'Change password',
    tag: 'User',
    auth: 'jwt',
    requestExample: { currentPassword: 'Demo1234!', newPassword: 'NewPass123!' },
  },
  {
    method: 'post',
    path: '/api/user/send-verification',
    summary: 'Send email verification',
    tag: 'User',
    auth: 'jwt',
  },
  {
    method: 'post',
    path: '/api/user/verify-email',
    summary: 'Verify email with code',
    tag: 'User',
    auth: 'jwt',
    requestExample: { email: 'user@example.com', verificationCode: '123456' },
  },
  {
    method: 'post',
    path: '/api/user/create-account',
    summary: 'Create account (extended registration flow)',
    tag: 'User',
    auth: 'jwt',
  },
  {
    method: 'post',
    path: '/api/user/send-email-change-verification',
    summary: 'Send email change verification',
    tag: 'User',
    auth: 'jwt',
  },
  {
    method: 'post',
    path: '/api/user/verify-email-change',
    summary: 'Confirm email change',
    tag: 'User',
    auth: 'jwt',
  },

  // ── Trading (internal DB sync) ─────────────────────────────────────────────
  {
    method: 'post',
    path: '/api/trading/initialize',
    summary: 'Initialize trading account for user',
    tag: 'Trading',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/trading/account',
    summary: 'Trading account snapshot',
    tag: 'Trading',
    auth: 'jwt',
  },
  {
    method: 'post',
    path: '/api/trading/sync',
    summary: 'Sync balances from broker',
    tag: 'Trading',
    auth: 'jwt',
  },
  {
    method: 'post',
    path: '/api/trading/sync-orders',
    summary: 'Sync orders from broker',
    tag: 'Trading',
    auth: 'jwt',
  },
  {
    method: 'post',
    path: '/api/trading/orders',
    summary: 'Place internal/paper trade order',
    tag: 'Trading',
    auth: 'jwt',
    requestExample: { symbol: 'AAPL', quantity: 1, side: 'buy', orderType: 'market' },
  },
  {
    method: 'get',
    path: '/api/trading/risk-settings',
    summary: 'Get risk management settings',
    tag: 'Trading',
    auth: 'jwt',
  },
  {
    method: 'put',
    path: '/api/trading/risk-settings',
    summary: 'Update risk management settings',
    tag: 'Trading',
    auth: 'jwt',
  },
  {
    method: 'delete',
    path: '/api/trading/orders/:orderId',
    summary: 'Cancel order',
    tag: 'Trading',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/trading/history',
    summary: 'Trade history',
    tag: 'Trading',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/trading/stats',
    summary: 'Trading statistics',
    tag: 'Trading',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/trading/positions',
    summary: 'Open trading positions',
    tag: 'Trading',
    auth: 'jwt',
  },
  {
    method: 'post',
    path: '/api/trading/positions/:symbol/close',
    summary: 'Close position for symbol',
    tag: 'Trading',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/trading/environment',
    summary: 'Trading environment (paper/live)',
    tag: 'Trading',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/trading/executions',
    summary: 'Order executions',
    tag: 'Trading',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/trading/sessions',
    summary: 'Trading sessions',
    tag: 'Trading',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/trading/orders',
    summary: 'List orders',
    tag: 'Trading',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/trading/health',
    summary: 'Trading subsystem health',
    tag: 'Trading',
    auth: 'jwt',
  },

  // ── Enhanced data (/api/data) ──────────────────────────────────────────────
  {
    method: 'get',
    path: '/api/data/quote/:symbol',
    summary: 'Aggregated quote for symbol',
    tag: 'Data',
    auth: 'jwt',
  },
  {
    method: 'post',
    path: '/api/data/quotes',
    summary: 'Bulk quotes (max 50 symbols)',
    tag: 'Data',
    auth: 'jwt',
    requestExample: { symbols: ['AAPL', 'MSFT'] },
  },
  {
    method: 'get',
    path: '/api/data/historical/:symbol',
    summary: 'Historical OHLCV data',
    tag: 'Data',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/data/news',
    summary: 'Aggregated news feed',
    tag: 'Data',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/data/sentiment/reddit',
    summary: 'Reddit sentiment snapshot',
    tag: 'Data',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/data/trading/sync',
    summary: 'Trigger trading data sync',
    tag: 'Data',
    auth: 'jwt',
  },
  {
    method: 'post',
    path: '/api/data/portfolio/refresh',
    summary: 'Bulk refresh portfolio prices',
    tag: 'Data',
    auth: 'jwt',
    requestExample: { symbols: ['AAPL', 'MSFT'] },
  },
  {
    method: 'get',
    path: '/api/data/status',
    summary: 'Data services status',
    tag: 'Data',
    auth: 'jwt',
  },
  {
    method: 'post',
    path: '/api/data/maintenance',
    summary: 'Run data maintenance (admin)',
    tag: 'Data',
    auth: 'jwt-admin',
  },
  {
    method: 'get',
    path: '/api/data/validate',
    summary: 'Validate data integrity',
    tag: 'Data',
    auth: 'jwt',
  },
  {
    method: 'delete',
    path: '/api/data/cache/expired',
    summary: 'Purge expired cache entries (admin)',
    tag: 'Data',
    auth: 'jwt-admin',
  },
  {
    method: 'get',
    path: '/api/data/analytics/usage',
    summary: 'API usage analytics',
    tag: 'Data',
    auth: 'jwt',
  },
  {
    method: 'get',
    path: '/api/data/scheduler/status',
    summary: 'Background scheduler status (admin)',
    tag: 'Data',
    auth: 'jwt-admin',
  },
  {
    method: 'post',
    path: '/api/data/scheduler/trigger/market',
    summary: 'Trigger market data job (admin)',
    tag: 'Data',
    auth: 'jwt-admin',
  },
  {
    method: 'post',
    path: '/api/data/scheduler/trigger/news',
    summary: 'Trigger news job (admin)',
    tag: 'Data',
    auth: 'jwt-admin',
  },
  {
    method: 'post',
    path: '/api/data/scheduler/trigger/sentiment',
    summary: 'Trigger sentiment job (admin)',
    tag: 'Data',
    auth: 'jwt-admin',
  },
  {
    method: 'post',
    path: '/api/data/scheduler/trigger/full',
    summary: 'Trigger full sync job (admin)',
    tag: 'Data',
    auth: 'jwt-admin',
  },
  {
    method: 'post',
    path: '/api/data/scheduler/trigger/maintenance',
    summary: 'Trigger maintenance job (admin)',
    tag: 'Data',
    auth: 'jwt-admin',
  },
];
